### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by SionoiS** [Defluencer/social_defluencer#3]
- [x] Clean Dependencies
- [x] Update READMEs & Docs
- [x] Update CLI
- [x] Test, Test, Test
- [x] Save CID on Pinata
- [x] Update social.defluencer.eth
- [x] Pin on local node
